# Generated by Django 4.2 on 2023-05-18 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinador',
            name='apellido',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='coordinador',
            name='nombre',
            field=models.CharField(max_length=20),
        ),
    ]
